---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netstat-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netstat-ui
  template:
    metadata:
      labels:
        app: netstat-ui
    spec:

      enableServiceLinks: false
      imagePullSecrets:
        - name: regcred
      containers:
        - name: netstat-ui
          image: netstat-ui
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: netstat-ui
  labels:
    app: netstat-ui
spec:
  selector:
    app: netstat-ui
  ports:
  - protocol: TCP
    port: 3001
