---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whois-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: whois-cache
  template:
    metadata:
      labels:
        app: whois-cache
    spec:
      enableServiceLinks: false
      containers:
        - name: whois
          image: codemowers/whois
          ports:
            - containerPort: 3005
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: whois-cache
  labels:
    app: whois-cache
spec:
  selector:
    app: whois-cache
  ports:
  - protocol: TCP
    port: 3005
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: netstat-aggregator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: netstat-aggregator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: netstat-aggregator
subjects:
- kind: ServiceAccount
  name: netstat-aggregator
  namespace: laurivosandi-jctkx
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: netstat-aggregator
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: netstat-aggregator
spec:
  selector:
    matchLabels:
      app: netstat-aggregator
  podMetricsEndpoints:
    - port: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netstat-aggregator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netstat-aggregator
  template:
    metadata:
      labels:
        app: netstat-aggregator
    spec:
      serviceAccountName: netstat-aggregator
      enableServiceLinks: false
      imagePullSecrets:
        - name: regcred
      containers:
        - name: netstat-aggregator
          image: netstat-aggregator
          ports:
            - containerPort: 3001
              name: http
          env:
            - name: URL_WHOIS_CACHE
              value: http://whois-cache:3005
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
---
apiVersion: v1
kind: Service
metadata:
  name: netstat-aggregator
  labels:
    app: netstat-aggregator
spec:
  selector:
    app: netstat-aggregator
  ports:
  - protocol: TCP
    port: 3001
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arch
  annotations:
    external-dns.alpha.kubernetes.io/target: traefik.codemowers.ee
    kubernetes.io/ingress.class: shared
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
    - hosts:
        - "*.codemowers.ee"
  rules:
    - host: "arch.codemowers.ee"
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: netstat-aggregator
                port:
                  number: 3001
