apiVersion: skaffold/v3
kind: Config
metadata:
  name: netstat-aggregator

deploy:
  kubectl: {}

manifests:
  rawYaml:
     - deployment.yaml

build:
  artifacts:
  - image: netstat-aggregator

portForward:
  - resourceType: deployment
    resourceName: netstat-aggregator
    port: 3001
    localPort: 3001
